### ISSUE TITLE
verification code is not showing

### ISSUE THREAD

**Issue by Jithendra18** [abhijadhav8308/Library-Management-System#1]
verification code is not loading. please help me

**Comment by abhijadhav8308** [comment]
**Make sure your "captcha.php" is in the same folder and contains the code** as below :-

`<?php 
session_start(); 
$text = rand(10000,99999); 
$_SESSION["vercode"] = $text; 
$height = 25; 
$width = 65;   
$image_p = imagecreate($width, $height); 
$black = imagecolorallocate($image_p, 0, 0, 0); 
$white = imagecolorallocate($image_p, 255, 255, 255); 
$font_size = 14; 
imagestring($image_p, $font_size, 5, 5, $text, $white); 
imagejpeg($image_p, null, 80); 
?>`

If this doesn't solve your issue and you want to **bypass the verification code**, then remove the below code. 

`if ($_POST["vercode"] != $_SESSION["vercode"] OR $_SESSION["vercode"]=='')  {
        echo "<script>alert('Incorrect verification code');</script>" ;
    } `

**Don't forget to remove the subsequent else part and the closing curly bracket. Also the required attribute in this tag** -> `<input type="text" class="form-control1"  name="vercode" maxlength="5" autocomplete="off" required  style="height:25px;" />&nbsp;<img src="captcha.php">`

**Comment by Smr777** [comment]
can you please explain a little more where to edit the above code

**Comment by khalliwete** [comment]
do i still need to delete the captcha file?

**Comment by sathish2503** [comment]
verification code is not loading. Now how to proceed further? The above steps are not useful

**Comment by abhijadhav8308** [comment]
Hello Guys, 

The captcha has been removed from the project.
