### ISSUE TITLE
admin login problem

### ISSUE THREAD

**Issue by MayankChoudhary123** [abhijadhav8308/Library-Management-System#3]
what are the  details for admin login

and thank you you are excellent user signup and sigin are working good

**Comment by keshavsinghmfp** [comment]
same issue....You got it resolved ?

**Comment by abhijadhav8308** [comment]
Hi Guys, 

I've used the email "phpgurukulofficial@gmail.com" and password "Test@123" for admin login, if you prefer something else you can modify it using dbms system.
